-- MySQL Script generated by MySQL Workbench
-- Fri Mar 27 11:13:46 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS = @@UNIQUE_CHECKS, UNIQUE_CHECKS = 0;
SET @OLD_FOREIGN_KEY_CHECKS = @@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS = 0;
SET @OLD_SQL_MODE = @@SQL_MODE, SQL_MODE =
        'ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb`;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8;
USE `mydb`;

-- -----------------------------------------------------
-- Table `mydb`.`blogs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `blogs` ;

CREATE TABLE IF NOT EXISTS `blogs` (
  `id` INT NOT NULL,
  `blog_title` VARCHAR(100) NOT NULL,
  `handle` VARCHAR(100) NULL,
  `datecreated` DATETIME NULL,
  `User_id` BIGINT(20) NOT NULL,
  UNIQUE INDEX `handle_UNIQUE` (`handle` ASC),
  PRIMARY KEY (`id`, `User_id`),
  INDEX `fk_blogs_User1_idx` (`User_id` ASC),
  CONSTRAINT `fk_blogs_User1`
    FOREIGN KEY (`User_id`)
    REFERENCES `users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`blogs_categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `blogs_categories`;

CREATE TABLE IF NOT EXISTS `blogs_categories`
(
    `blogs_id`      INT        NOT NULL,
    `blogs_User_id` BIGINT(20) NOT NULL,
    `categories_id` INT        NOT NULL,
    PRIMARY KEY (`blogs_id`, `blogs_User_id`, `categories_id`),
    INDEX `fk_blogs_has_categories_categories1_idx` (`categories_id` ASC),
    INDEX `fk_blogs_has_categories_blogs1_idx` (`blogs_id` ASC, `blogs_User_id` ASC),
    CONSTRAINT `fk_blogs_has_categories_blogs1`
        FOREIGN KEY (`blogs_id`, `blogs_User_id`)
            REFERENCES `blogs` (`id`, `User_id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `fk_blogs_has_categories_categories1`
        FOREIGN KEY (`categories_id`)
            REFERENCES `categories` (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `categories`;

CREATE TABLE IF NOT EXISTS `categories`
(
    `id`   INT          NOT NULL,
    `name` VARCHAR(255) NOT NULL,
    PRIMARY KEY (`id`)
);


-- -----------------------------------------------------
-- Table `mydb`.`images`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `images`;

CREATE TABLE IF NOT EXISTS `images`
(
    `id`          INT          NOT NULL,
    `url`         VARCHAR(250) NULL,
    `small_size`  VARCHAR(150) NULL,
    `medium_size` VARCHAR(150) NULL,
    `caption`     TEXT(500)    NULL,
    `date`        DATETIME     NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `User_id`     BIGINT(20)   NOT NULL,
    PRIMARY KEY (`id`, `User_id`),
    INDEX `fk_images_User1_idx` (`User_id` ASC),
    CONSTRAINT `fk_images_User1`
        FOREIGN KEY (`User_id`)
            REFERENCES `users` (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`posts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `posts`;

CREATE TABLE IF NOT EXISTS `posts`
(
    `id`               INT          NOT NULL,
    `texttitle`        VARCHAR(45)  NOT NULL,
    `textbody`         VARCHAR(300) NOT NULL,
    `link_url`         VARCHAR(300) NULL,
    `link_title`       VARCHAR(45)  NULL,
    `link_caption`     VARCHAR(45)  NULL,
    `video_embed_code` VARCHAR(450) NULL,
    `post_status`      VARCHAR(45)  NULL,
    `date_created`     DATETIME     NULL,
    PRIMARY KEY (`id`)
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`posts_categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `posts_categories`;

CREATE TABLE IF NOT EXISTS `posts_categories`
(
    `categories_id` INT NOT NULL,
    `posts_id`      INT NOT NULL,
    PRIMARY KEY (`categories_id`, `posts_id`),
    INDEX `fk_categories_has_posts_posts1_idx` (`posts_id` ASC),
    INDEX `fk_categories_has_posts_categories1_idx` (`categories_id` ASC),
    CONSTRAINT `fk_categories_has_posts_categories1`
        FOREIGN KEY (`categories_id`)
            REFERENCES `categories` (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `fk_categories_has_posts_posts1`
        FOREIGN KEY (`posts_id`)
            REFERENCES `posts` (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
);


-- -----------------------------------------------------
-- Table `mydb`.`posts_images`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `posts_images`;

CREATE TABLE IF NOT EXISTS `posts_images`
(
    `posts_id`  INT NOT NULL,
    `images_id` INT NOT NULL,
    PRIMARY KEY (`posts_id`, `images_id`),
    INDEX `fk_posts_has_images_images1_idx` (`images_id` ASC),
    INDEX `fk_posts_has_images_posts1_idx` (`posts_id` ASC),
    CONSTRAINT `fk_posts_has_images_posts1`
        FOREIGN KEY (`posts_id`)
            REFERENCES `posts` (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `fk_posts_has_images_images1`
        FOREIGN KEY (`images_id`)
            REFERENCES `images` (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `users` ;

CREATE TABLE IF NOT EXISTS `users` (
  `username` VARCHAR(200) NOT NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(225) NOT NULL,
  `firstname` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `id` BIGINT(20) NOT NULL,
  `blogsfollowed` INT NULL,
  `profilepicture` TEXT(200) NULL,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  INDEX `username_UNIQUE` (`username` ASC),
  FULLTEXT INDEX `lastname` (`username`),
  PRIMARY KEY (`id`));


SET SQL_MODE = @OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS = @OLD_UNIQUE_CHECKS;
