use kitsune_db;
delete from categories where 1=1;
insert into categories values (1, 'Math');
insert into categories values (2, 'Science');
insert into categories values (3, 'History');
insert into categories values (4, 'Computer Science');
insert into categories values (5, 'Data Science');
insert into categories values (6, 'Web Development');
insert into categories values (7, 'Physical Education');
insert into categories values (8, 'Music');
insert into categories values (9, 'Dance');
insert into categories values (10, 'Astronomy');
insert into categories values (11, 'Psychology/Sociology');
insert into categories values (12, 'Government');
insert into categories values (13, 'Health');
insert into categories values (14, 'Religion');
insert into categories values (15, 'Entertainment');